# Generated by Django 5.1.4 on 2025-02-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='professional_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='publications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
