# Generated by Django 5.1.4 on 2025-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blogpost_content_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
