# Generated by Django 5.1.4 on 2025-07-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newspost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={},
        ),
        migrations.AddField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
