# Generated by Django 5.1.4 on 2025-07-14 16:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_newspost_options_newspost_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='newspost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
