# Generated by Django 5.1.4 on 2026-05-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_teammember_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('press_release', 'Press Release'), ('update', 'Project Update'), ('event', 'Event'), ('partnership', 'Partnership')], default='update', max_length=50),
        ),
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. Geospatial, Research)', max_length=255),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
