# Generated by Django 5.1.4 on 2026-05-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newspost_category_newspost_image_newspost_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
