# Generated by Django 5.1.4 on 2026-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newspost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('research', 'Research & Analysis'), ('evaluation', 'Monitoring & Evaluation'), ('data_collection', 'Data Collection'), ('strategy', 'Strategic Planning'), ('capacity_building', 'Capacity Building'), ('digital', 'Digital Solutions')], default='research', max_length=50),
        ),
    ]
