# Generated by Django 5.1.4 on 2026-05-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('research', 'Research & Analysis'), ('evaluation', 'Monitoring & Evaluation'), ('data_collection', 'Data Collection'), ('strategy', 'Strategic Planning'), ('capacity_building', 'Capacity Building'), ('digital', 'Digital Solutions'), ('endline_evaluation', 'Endline Evaluation'), ('technical_consultancy', 'Technical Consultancy'), ('fiscal_policy', 'Fiscal Policy'), ('governance', 'Governance'), ('policy_advisory', 'Policy Advisory'), ('education', 'Education'), ('socio_economic', 'Socio-Economic Analysis'), ('human_rights', 'Human Rights'), ('poverty', 'Poverty & Development'), ('agriculture', 'Agriculture'), ('microfinance', 'Microfinance'), ('labour', 'Labour & Informal Economy'), ('climate', 'Climate Change'), ('health', 'Health')], default='research', max_length=50),
        ),
    ]
