# Generated by Django 5.1.4 on 2026-05-13 16:58

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_blogpost_image_alter_newspost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('application_form', cloudinary.models.CloudinaryField(blank=True, help_text='Upload the application form (e.g. .docx or .pdf)', max_length=255, null=True, verbose_name='form')),
                ('job_description_pdf', cloudinary.models.CloudinaryField(blank=True, help_text='Upload the full job description PDF', max_length=255, null=True, verbose_name='pdf')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(default='Freetown, Sierra Leone', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('part_time', 'Part-time')], default='full_time', max_length=20)),
                ('closing_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Vacancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
