# Generated by Django 5.1.4 on 2026-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobvacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='application_form',
            field=models.URLField(blank=True, help_text='Link to the Google Form for applications', null=True),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('contract', 'Contract'), ('short_contract', 'Short Contract'), ('internship', 'Internship'), ('part_time', 'Part-time')], default='full_time', max_length=20),
        ),
    ]
