# Generated by Django 5.1.4 on 2026-06-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_jobvacancy_application_form_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True)]},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
